#### https://gist.github.com/yonglai/d4617d6914d5f4eb22e4e5a15c0e9a03
---
- name: "Install docker on a Centos 7 machine"
  gather_facts: false
  hosts: all
  become: true

  tasks:

    - name: Remove docker if installed from CentOS repo
      yum:
        name: "{{ item }}"
        state: removed

      with_items:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine

    - name: Install yum utils
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
    - name: Enable Docker Edge & Test repo      
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      
    - name: Install Docker
      yum:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        
    - name: Convert old images to new runtime
      shell:
        cmd: " grep -rl 'docker-runc' /var/lib/docker/containers/ | xargs sed -i 's/docker-runc/runc/g' "
      changed_when: false
      failed_when: false

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
  
    - name: Add user akakanu to docker group
      user:
        name: akakanu
        groups: docker
        append: yes