---
- name: "Install docker on a Centos 7 machine"
  gather_facts: false
  hosts: all
  become: yes
  tasks:
    - name: "Installing Docker Prerequisite packages"
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: install python-setuptools by yum
      yum:
        name: python-setuptools
        state: present
        update_cache: yes
    - name: "Configuring docker-ce repo"
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
    - name: " Installing Docker latest version"
      yum:
        name: docker-ce
        state: present
    - name: "Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes"
      systemd:
        daemon_reload: true
    - name: "Install Docker Engine"
      apt:
        name: docker.io
        state: present
    - name: "Install Docker CLI"
      apt:
        name: docker-compose
        state: present
    - name: "Enable the Docker daemon in systemd"
      systemd:
        name: docker
        enabled: yes
        masked: no
    - name: "Start the Docker daemon"
      systemd:
        name: docker
        state: started
        masked: no
    