---
- name: "install webapp-aka v1"
  become: yes
  hosts: prod
  tags: webapp-aka_v1
  
  tasks:
    - name: "Remove folder"
      file:
        path: "/home/{{ ansible_user }}/webapp"
        state: absent
    - name: Create webapp directory
      file:
        path: "/home/{{ ansible_user }}/webapp/"
        state: directory
    - name: "Install git"
      yum:
        name: git
        state: present
        update_cache: yes
    - name: "git clone to folder"
      git:
        repo: https://github.com/diranetafen/static-website-example.git
        dest: /home/{{ ansible_user }}/webapp/

    - name: Add static site config files
      template:
        src: templates/index.html.j2
        dest: "/home/{{ ansible_user }}/webapp/index.html"
    - name: "Launching an HTTPD Container"
      docker_container:
        name: apache-server
        image: httpd
        state: started
        ports:
          - "8000:80"
        volumes:
          - /home/{{ ansible_user }}/webapp:/usr/local/apache2/htdocs/
...